### ISSUE TITLE
endian.h not found on macOS

### ISSUE THREAD

**Issue by EricFromCanada** [openwall/passwdqc#15]
The reference to <endian.h> in [passwdqc_filter.h](https://github.com/openwall/passwdqc/blob/main/passwdqc_filter.h#L38) needs to be <machine/endian.h> for it to compile on macOS.

**Comment by solardiz** [comment]
Thank you, @EricFromCanada! Does `<machine/endian.h>` define `__BYTE_ORDER`, `__BIG_ENDIAN`, and `__LITTLE_ENDIAN`? If not, then including it is of no use.

Since this is just an optimization anyhow, I'm tempted to treat macOS the same as MSVC there, like this:

```diff
-#ifndef _MSC_VER
+#if !defined(_MSC_VER) && !defined(__APPLE__)
 #include <endian.h>
 #endif
```

Does this work?

**Comment by EricFromCanada** [comment]
`machine/endian.h` includes [`i386/endian.h`](https://opensource.apple.com/source/xnu/xnu-7195.81.3/bsd/i386/endian.h.auto.html) which defines `BYTE_ORDER`, `BIG_ENDIAN` and `LITTLE_ENDIAN` via [`sys/_endian.h`](https://opensource.apple.com/source/xnu/xnu-7195.81.3/bsd/sys/_endian.h.auto.html), but it also looks like those [aren't necessarily needed](https://github.com/stbrumme/hash-library/issues/1) since you can assume little endian on macOS for Intel and ARM.

**Comment by solardiz** [comment]
> defines `BYTE_ORDER`, `BIG_ENDIAN` and `LITTLE_ENDIAN`

However, these are not the "underscored" versions that `passwdqc_filter.h` currently uses.

> via [`sys/_endian.h`](https://opensource.apple.com/source/xnu/xnu-7195.81.3/bsd/sys/_endian.h.auto.html)

Not, it defines those directly. That other file only defines the conversions.

> you can assume little endian on macOS for Intel and ARM.

But not on PowerPC.

Overall, I'm tempted not to over-complicate this, and use the simpler patch I suggested above. The optimization would then continue to work for Linux and *BSDs. I guess large files would most commonly be processed with `pwqfilter` on Linux.

**Comment by solardiz** [comment]
> I'm tempted to treat macOS the same as MSVC there, like this:
> 
> ```diff
> -#ifndef _MSC_VER
> +#if !defined(_MSC_VER) && !defined(__APPLE__)
>  #include <endian.h>
>  #endif
> ```
> 
> Does this work?

@EricFromCanada Can you please test this specific change? Thanks!

**Comment by EricFromCanada** [comment]
Yes, that seems to work.
