### ISSUE TITLE
passwdqc enforces rules on root user invocations even when configured not to

### ISSUE THREAD

**Issue by jukuisma** [openwall/passwdqc#27]
Hey,

passwdqc enforces its rules for root user invocations even when configured to
`enforce=users`. This applies specifically to `chpasswd` command. `passwd`
warns of the weak password but doesn't fail as documented in passwdqc.conf(5):

    $ chpasswd > /dev/null
    user1:weak
    Weak password: too short.
    Weak password: too short.
    Weak password: too short.
    chpasswd: (user user1) pam_chauthtok() failed, error:
    Authentication token manipulation error
    chpasswd: (line 1, user user1) password not changed
    $ echo $?
    1

    $ passwd user1 > /dev/null
    Enter new password:
    Weak password: too short.
    Re-type new password:
    passwd: password updated successfully
    $ echo $?
    0

Relevant pam configuration used:

    $ cat /etc/pam.d/chpasswd 
    # The PAM configuration file for the Shadow 'chpasswd' service
    #

    @include common-password

    $ cat /etc/pam.d/passwd 
    #
    # The PAM configuration file for the Shadow `passwd' service
    #

    @include common-password

    $ grep ^password /etc/pam.d/common-password 
    password	requisite			pam_passwdqc.so enforce=users
    password	[success=1 default=ignore]	pam_unix.so obscure use_authtok try_first_pass yescrypt
    password	requisite			pam_deny.so
    password	required			pam_permit.so

This might be caused by `chpasswd` interpreting passwdqc warnings written to
STDERR as failures.

I reported this already here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038719. But based on my quick perusing, this also affects upstream.

Cheers,
Juho Kuisma

**Comment by ldv-alt** [comment]
I've never tried to use `chpasswd` with `pam_passwdqc` before, now I tried and it looks odd: `chpasswd` complains about conversation error but the password is set, nevertheless.   Maybe it depends on the version of `chapsswd`.

**Comment by jukuisma** [comment]
I'm sporting:

    $ dpkg -l passwd | grep ii
    ii  passwd         1:4.13+dfsg1-1+b1 amd64        change and administer password and group data

from here: https://packages.debian.org/bookworm/passwd. Tried compiling
`passwdqc` with the weak password warnings silenced, but it still fails:

    $ chpasswd > /dev/null
    user1:weak
    chpasswd: (user user1) pam_chauthtok() failed, error:
    Authentication token manipulation error
    chpasswd: (line 1, user user1) password not changed
    $ echo $?
    1

i.e., it's not simply the STDERR messages breaking this. I can also try some
other distros to see if I can get this working on some other `chpasswd` version
to narrow this down a bit.

**Comment by jukuisma** [comment]
The code seems to enter this if block: https://github.com/openwall/passwdqc/blob/main/pam_passwdqc.c#L510, which causes the error.

**Comment by jukuisma** [comment]
Sure, ran:

    $ sudo strace -s 1024 -fo strace.out chpasswd > /dev/null

It does read:

    $ grep /etc/pam.d/chpasswd strace.out
    911   openat(AT_FDCWD, "/etc/pam.d/chpasswd", O_RDONLY) = 3

And runs as root:

    $ grep getuid strace.out
    911   getuid()                          = 0
    911   getuid()                          = 0

Also the `enforce=users` seems to be picked up, because it does work correctly with `passwd`. Something just goes wrong with `chpasswd`. Also, dropping `pam_passwdqc.so`  from `/etc/pam.d/common-password` fixes `chpasswd`.

**Comment by solardiz** [comment]
Oh, I now see we're actually limiting the effect of `enforce=users` to `passwd` here: https://github.com/openwall/passwdqc/blob/4d1742b050aa7dd252c0aaf0503b9616754ceef6/pam_passwdqc.c#L299

And here's why:

```
commit bf3618bf56ecf2e434ed99d46ce87e6f006d2c3e
Author: Solar Designer <solar@openwall.com>
Date:   Sat Nov 1 02:02:31 2003 +0300

    Assume invocation by root only if both the UID is 0 and the PAM service
    name is "passwd"; this should solve changing expired passwords on Solaris
    and HP-UX and make "enforce=users" safe.
```

but now I wish I recorded even more detail on the rationale/problems.

**Comment by solardiz** [comment]
The referenced commit also removed this text from `README`:

```
Please note that "enforce=users" may not actually enforce strong
passwords with services other than the passwd command, that depends on
what UID the services run as when they invoke PAM.
```

**Comment by jukuisma** [comment]
Sounds great to me! Tested:

    $ git diff
    diff --git a/pam_passwdqc.c b/pam_passwdqc.c
    index b421fa8..ab19d65 100644
    --- a/pam_passwdqc.c
    +++ b/pam_passwdqc.c
    @@ -296,7 +296,7 @@ static int am_root(pam_handle_t *pamh)
                    return 0;
            service = item;

    -       return !strcmp(service, "passwd");
    +       return strcmp(service, "passwd") || strcmp(service, "chpasswd");
     }

     PAM_EXTERN int pam_sm_chauthtok(pam_handle_t *pamh, int flags,

and it works.

**Comment by ldv-alt** [comment]
>     2. Document that `enforce=users` is only effective for these two services.

Like this?

The `users` setting is like `everyone` for all PAM services except `chpasswd` and `passwd`. For these two PAM services `users` setting will enforce strong passwords for invocations by non-root users only.

**Comment by jukuisma** [comment]
I will be completely unavailable until the start of July. This issue can be closed if/when this is merged: https://github.com/openwall/passwdqc/pull/28. I verified that it fixes the original issue on Debian 12.

Didn't take long to fix it. Thanks guys, great work!

**Comment by solardiz** [comment]
> e.g. `sshd` could be invoking the PAM stack as root on login, and if change of expired password is forced then with `enforce=users` and no service name check a non-root user would bypass password policy.

It appears that FreeBSD's copy/fork of pam_passwdqc might be lacking the commit from 2003 referenced above that would fix that issue, as people were reporting it in 2018:

https://forums.freebsd.org/threads/expired-password-change-not-using-pam_passwdqc.64522/#post-375626

Indeed, they appear to use a version from 2002:

https://cgit.freebsd.org/src/tree/contrib/pam_modules/pam_passwdqc

Perhaps we should recommend them to upgrade at least to pam_passwdqc 1.0.5, which we released in 2008.

**Comment by jukuisma** [comment]
> Perhaps we should recommend them to upgrade at least to pam_passwdqc 1.0.5, which we released in 2008.

Can't hurt to give them a heads up. It's up to them what they'll do with the info.

**Comment by solardiz** [comment]
A different issue, but since FreeBSD's outdated pam_passwdqc was mentioned in here, also adding to here: I've just confirmed that this FreeBSD pam_passwdqc bug https://forums.freebsd.org/threads/enforcing-password-quality-with-pam.82077/ https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258535 "Not having a NUMBER in min position N3 of pam_passwdqc.so configuration causes in valid password size" is not reproducible on our latest version (maybe we never had this bug, or maybe fixed long ago - but I don't recall ever running into this issue).

I still haven't pinged FreeBSD about updating. Maybe someone should.
